/**
 * graph8 /search/contacts filter vocab — verified live 2026-09-27 07:10 PKT via
 * `GET /search/filter-options?resource=contacts&fields=<field>` (one field per call).
 * Industry values are LinkedIn-style labels matched with `any_of` (exact). "fintech" matches nothing (spec open item 1);
 * `contains` also works on company_industry ("FinTech" → a few multi-label rows).
 */
export const SENIORITY = ['CXO', 'Vice President', 'Director', 'Owner / Partner', 'Experienced Manager', 'Senior', 'Entry Level', 'In Training'] as const;

/** Ordered small → large; used for "adjacent/bigger size" widening and scoring. */
export const SIZES = ['1-10', '11-50', '51-200', '201-500', '501-1000', '1001-5000', '5001-10000', '10001+'] as const;

export const DEPARTMENTS = [
  'Administrative', 'Arts and Design', 'Consulting', 'Customer Success and Support', 'Education', 'Engineering', 'Finance',
  'Healthcare Services', 'Human Resources', 'Legal', 'Marketing', 'Media and Communication', 'Operations', 'Other',
  'Research', 'Sales', 'Science', 'Skilled Trades',
] as const;

/** Single-label industries with ≥ 20k contacts, most common first (311 values). */
export const INDUSTRIES: readonly string[] = [
  "IT Services and IT Consulting",
  "Hospitals and Health Care",
  "Retail",
  "Higher Education",
  "Financial Services",
  "Software Development",
  "Government Administration",
  "Construction",
  "Banking",
  "Business Consulting and Services",
  "Real Estate",
  "Telecommunications",
  "Insurance",
  "Motor Vehicle Manufacturing",
  "Education Administration Programs",
  "Oil and Gas",
  "Hospitality",
  "Food and Beverage Services",
  "Advertising Services",
  "Non-profit Organizations",
  "Manufacturing",
  "Pharmaceutical Manufacturing",
  "Restaurants",
  "Primary and Secondary Education",
  "Wellness and Fitness Services",
  "Industrial Machinery Manufacturing",
  "Utilities",
  "Food and Beverage Manufacturing",
  "Staffing and Recruiting",
  "Accounting",
  "Airlines and Aviation",
  "Education",
  "Machinery Manufacturing",
  "Chemical Manufacturing",
  "Law Practice",
  "Mining",
  "Information Technology and Services",
  "Medical Practices",
  "Research Services",
  "Retail Apparel and Fashion",
  "Truck Transportation",
  "Civil Engineering",
  "Wholesale",
  "Human Resources Services",
  "Entertainment Providers",
  "Environmental Services",
  "Consumer Services",
  "Facilities Services",
  "Medical Equipment Manufacturing",
  "Professional Training and Coaching",
  "Outsourcing and Offshoring Consulting",
  "Professional Services",
  "Travel Arrangements",
  "Architecture and Planning",
  "Individual and Family Services",
  "Wholesale Building Materials",
  "Defense and Space Manufacturing",
  "Biotechnology Research",
  "Automation Machinery Manufacturing",
  "Legal Services",
  "Farming",
  "Design Services",
  "Civic and Social Organizations",
  "Armed Forces",
  "Security and Investigations",
  "Aviation and Aerospace Component Manufacturing",
  "Spectator Sports",
  "Broadcast Media Production and Distribution",
  "Computers and Electronics Manufacturing",
  "Semiconductor Manufacturing",
  "Engineering Services",
  "Education Management",
  "Mental Health Care",
  "Personal Care Product Manufacturing",
  "Textile Manufacturing",
  "Media Production",
  "Events Services",
  "Marketing Services",
  "Information Services",
  "E-Learning Providers",
  "Investment Management",
  "International Trade and Development",
  "Automotive",
  "Law Enforcement",
  "Packaging and Containers Manufacturing",
  "Maritime Transportation",
  "Book and Periodical Publishing",
  "Computer and Network Security",
  "Plastics Manufacturing",
  "Wholesale Import and Export",
  "Retail Groceries",
  "Retail Luxury Goods and Jewelry",
  "Furniture and Home Furnishings Manufacturing",
  "Food & Beverages",
  "Printing Services",
  "Unclassified",
  "Non-profit Organization Management",
  "Religious Institutions",
  "Public Relations and Communications Services",
  "Venture Capital and Private Equity Principals",
  "Computer Hardware Manufacturing",
  "Renewable Energy Semiconductor Manufacturing",
  "Retail Office Equipment",
  "Freight and Package Transportation",
  "Executive Offices",
  "Musicians",
  "Public Safety",
  "International Affairs",
  "Computer Games",
  "Paper and Forest Product Manufacturing",
  "Mechanical or Industrial Engineering",
  "Newspaper Publishing",
  "Food Production",
  "Rail Transportation",
  "Government Relations Services",
  "Administration of Justice",
  "Graphic Design",
  "Beverage Manufacturing",
  "Transportation/Trucking/Railroad",
  "Market Research",
  "Motor Vehicle Parts Manufacturing",
  "Retail Art Supplies",
  "Consumer Goods",
  "Photography",
  "Gambling Facilities and Casinos",
  "Research",
  "Online Audio and Video Media",
  "Performing Arts",
  "Internet Publishing",
  "Renewable Energy Power Generation",
  "Veterinary Services",
  "Apparel and Fashion",
  "Building Materials",
  "Aviation & Aerospace",
  "Investment Banking",
  "Health and Human Services",
  "Recreational Facilities",
  "Services for Renewable Energy",
  "Sporting Goods Manufacturing",
  "Retail Motor Vehicles",
  "Writing and Editing",
  "Entertainment",
  "Retail Pharmacies",
  "Internet Marketplace Platforms",
  "Human Resources",
  "Public Policy Offices",
  "Computer Networking Products",
  "Translation and Localization",
  "Medical Devices",
  "Shipbuilding",
  "Capital Markets",
  "Artists and Writers",
  "Biotechnology",
  "Leasing Non-residential Real Estate",
  "Holding Companies",
  "Strategic Management Services",
  "Animation and Post-production",
  "Political Organizations",
  "Warehousing and Storage",
  "Electric Power Generation",
  "Alternative Medicine",
  "Design",
  "Outsourcing/Offshoring",
  "Energy Technology",
  "Libraries",
  "Philanthropic Fundraising Services",
  "Renewables & Environment",
  "Urban Transit Services",
  "Retail Health and Personal Care Products",
  "Medical and Diagnostic Laboratories",
  "IT System Custom Software Development",
  "Think Tanks",
  "E-Learning",
  "Sporting Goods",
  "Dairy Product Manufacturing",
  "Cosmetics",
  "Ground Passenger Transportation",
  "Industrial Automation",
  "Furniture",
  "Railroad Equipment Manufacturing",
  "Public Health",
  "Home Health Care Services",
  "Renewable Energy Equipment Manufacturing",
  "Business Content",
  "Packaging and Containers",
  "Tobacco Manufacturing",
  "Food and Beverage Retail",
  "Business Supplies and Equipment",
  "Consumer Electronics",
  "Vehicle Repair and Maintenance",
  "Data Infrastructure and Analytics",
  "Fundraising",
  "Defense & Space",
  "Wireless Services",
  "Transportation Equipment Manufacturing",
  "Interior Design",
  "Maritime",
  "Fabricated Metal Products",
  "Building Construction",
  "Sports Teams and Clubs",
  "Solar Electric Power Generation",
  "Technical and Vocational Training",
  "Luxury Goods and Jewelry",
  "Electrical Equipment Manufacturing",
  "Fisheries",
  "Legislative Offices",
  "Music",
  "Online Media",
  "Security Systems Services",
  "Government Relations",
  "Ranching",
  "Import and Export",
  "Semiconductors",
  "Primary Metal Manufacturing",
  "Wholesale Motor Vehicles and Parts",
  "Paper and Forest Products",
  "Repair and Maintenance",
  "Social Networking Platforms",
  "Wholesale Food and Beverage",
  "Insurance Agencies and Brokerages",
  "Commercial and Industrial Machinery Maintenance",
  "HVAC and Refrigeration Equipment Manufacturing",
  "Wine and Spirits",
  "Real Estate Agents and Brokers",
  "Media & Telecommunications",
  "Community Services",
  "Space Research and Technology",
  "Agricultural Chemical Manufacturing",
  "Artificial Intelligence",
  "Operations Consulting",
  "Specialty Trade Contractors",
  "Apparel Manufacturing",
  "Computer Hardware",
  "Sports and Recreation Instruction",
  "Measuring and Control Instrument Manufacturing",
  "Nanotechnology Research",
  "Retail Furniture and Home Furnishings",
  "Security Guards and Patrol Services",
  "Mobile Gaming Apps",
  "Alternative Dispute Resolution",
  "Veterinary",
  "IT System Data Services",
  "Public Policy",
  "Healthcare",
  "Nursing Homes and Residential Care Facilities",
  "Fire Protection",
  "Dentists",
  "Child Day Care Services",
  "Commercial Real Estate",
  "Industry Associations",
  "Landscaping Services",
  "Robotics Engineering",
  "Hotels and Motels",
  "Internet News",
  "Hospitals",
  "Telephone Call Centers",
  "Blockchain Services",
  "Online and Mail Order Retail",
  "Blogs",
  "Nuclear Electric Power Generation",
  "Professional Organizations",
  "Wood Product Manufacturing",
  "Commercial and Industrial Equipment Rental",
  "Fine Art",
  "Equipment Rental Services",
  "Program Development",
  "Personal Care Services",
  "Book Publishing",
  "Language Schools",
  "Business Intelligence Platforms",
  "Climate Technology Product Manufacturing",
  "Animal Feed Manufacturing",
  "Glass Product Manufacturing",
  "Data Security Software Products",
  "Metal Treatments",
  "Warehousing",
  "Arts and Crafts",
  "Dairy",
  "Embedded Software Products",
  "Residential Building Construction",
  "Retail Gasoline",
  "Footwear Manufacturing",
  "Movies and Sound Recording",
  "Electric Lighting Equipment Manufacturing",
  "Golf Courses and Country Clubs",
  "Philanthropy",
  "Administrative and Support Services",
  "Office Furniture and Fixtures Manufacturing",
  "Housing and Community Development",
  "Pet Services",
  "Computer Networking",
  "Wholesale Chemical and Allied Products",
  "School and Employee Bus Services",
  "Wholesale Drugs and Sundries",
  "Janitorial Services",
  "Government",
  "Wholesale Metals and Minerals",
  "Museums",
  "Community Development and Urban Planning",
  "Wholesale Machinery",
  "Architectural and Structural Metal Manufacturing",
  "Commercial and Service Industry Machinery Manufacturing",
  "Waste Treatment and Disposal",
  "Mobile Computing Software Products",
  "Radio and Television Broadcasting",
  "Wineries",
  "Courts of Law",
  "Water Supply and Irrigation Systems",
  "Utilities Administration",
  "Executive Search Services",
  "Animation"
];

const lc = (s: string) => s.toLowerCase().trim();
const INDUSTRY_BY_LC = new Map(INDUSTRIES.map((v) => [lc(v), v]));
const SENIORITY_BY_LC = new Map(SENIORITY.map((v) => [lc(v), v as string]));
const SIZE_BY_LC = new Map(SIZES.map((v) => [lc(v), v as string]));

export const pickIndustry = (v: string) => INDUSTRY_BY_LC.get(lc(v));
export const pickSeniority = (v: string) => SENIORITY_BY_LC.get(lc(v));
export const pickSize = (v: string) => SIZE_BY_LC.get(lc(v));
